FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

LABEL maintainer="Jager <im@zhang.ge>"
LABEL description="FastKit 开发测试镜像"

# 安装系统依赖
RUN sed -i 's/deb.debian.org/mirrors.cloud.tencent.com/' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && \
    apt-get install gcc g++ libsnappy-dev curl default-libmysqlclient-dev net-tools locales vim procps -y && \
    apt-get clean && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    echo "zh_CN.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen

# 更新pip
RUN pip3 install --upgrade pip 

# 安装依赖插件
COPY requirements.txt /tmp/requirements.txt
RUN pip install \
    --no-cache-dir \
    -r /tmp/requirements.txt

WORKDIR /fastkit

COPY . .

RUN python setup.py install --single-version-externally-managed --record=installed_files.txt
